### ISSUE TITLE
Validate that resource is valid JSON-LD on PUT/POST

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#136]
This should be done in the endpoint, not openapi.yml. If validation fails, a 400 should be returned.

The motivation for this is because we have had cases of users submitting bad JSON-LD directly to the API (not via Sinopia Editor.)

**Comment by ndushay** [comment]
from JLitt:

> like here: 

https://github.com/LD4P/sinopia_editor/blob/main/src/utilities/Utilities.js#L90-L112
