### ISSUE TITLE
Add "edit_groups" for GET/POST/PUT resource endpoint

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#139]
* Add to openapi as an array of strings.
* Also, save to version entry when performing a POST/PUT. See https://github.com/LD4P/sinopia_api/blob/main/src/endpoints/resources.js#L215-L219

**Comment by ndushay** [comment]
Should it be `edit_groups` or `editGroups` in the API?  We have camelcase from bibframe things, but everything else is a single word.

Also, should edit groups be a required part of a resource?

**Comment by ndushay** [comment]
Given how Mongo has `edit_groups`, I'm going to stick with edit_groups.

As for making it required:
# make it required
# get tests to pass
# make it optional
# create PR
# make a ticket to change it to required after database migration
