### ISSUE TITLE
Add label to groups endpoint and return all groups instead of searching resources

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#143]
~~* Get groups from Cognito. See https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListGroups.html~~
* Hardcode groups in groups response
* For each group, return id and label (currently just returns id).
* Update openapi.yml to indicate structure of return object

**Comment by peetucket** [comment]
Groups in sinopia_editor: https://github.com/LD4P/sinopia_editor/blob/main/src/Config.js#L134-L160

**Comment by justinlittman** [comment]
Response should look like:
```
[
  {id: "stanford", "label": "Stanford University"},
  {id: "cornell", "label": "Cornell University"},
  ...
]
```
