### ISSUE TITLE
Create transfer endpoint

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#145]
The endpoint will be structured like `PUT /transfer/{resourceId}/{group}/{target}`

At present, the only value for _target_ is "ils". In the future, you can imagine it having additional values like "discovery".

The controller will:
* Verify that the user is a member of the group. (Note that the resource does NOT need to be associated with the group; a user can request the transfer of any resource regardless of the resource's groups.)
* Submit an SQS message requesting the transfer.

The name of queue will be `{group}-{target}`.

The message body will be serialized JSON with the following structure:
```
{
  "resource": {
    "uri": "{resourceURI -- full URI, not just resourceId}"
  },
  "user": {
    "email": "{user email}"
  },
  "group": "{group}",
  "target": "{target}"
}
```

The message will have an message attribute named `timestamp` that will contain the timestamp that the message is created formatted as ISO 8601.

**Comment by jermnelson** [comment]
Looks good; I have a few questions below:

1. Looking through the AWS [SQS message attributes](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-attributes) should we also include a timestamp in the attributes? With a limit of 10 message attributes, that still leaves us with 5
2. I'm not sure we can have nested attributes like `resource.uri` or `user.email`, if that is the case, maybe change from `resource` to `resource-uri` and `user` to `user-email`. 
3. Another approach would be just serialize the message format above to a string and store in the message body and the consuming application could read the message body as JSON

**Comment by justinlittman** [comment]
Yes, I mean the JSON structure to be the message body. Clarified above.

Added a timestamp attribute above as well.

**Comment by jermnelson** [comment]
I would propose that we simplify the SQS queue by removing the `target` as part of the queue name. Each group will have it's own queue and we can either add another field & value to the message body or to the message attributes if we need additional context.

**Comment by justinlittman** [comment]
Also, email should be extracted from the JWT token, which is available on `req.user`, e.g.,
```
{
api_1  |   sub: '449f003b-19d1-48b5-aecb-b4f47fbb7dc8',
api_1  |   aud: '2u6s7pqkc1grq1qs464fsi82at',
api_1  |   'cognito:groups': [ 'cornell' ],
api_1  |   email_verified: true,
api_1  |   event_id: 'e4ac6808-eba5-4360-8e55-64ee0b7af9eb',
api_1  |   token_use: 'id',
api_1  |   auth_time: 1631910380,
api_1  |   iss: 'https://cognito-idp.us-west-2.amazonaws.com/us-west-2_CGd9Wq136',
api_1  |   'cognito:username': 'jlittman',
api_1  |   exp: 1632007148,
api_1  |   iat: 1632003548,
api_1  |   email: 'justinlittman@stanford.edu'
api_1  | }
```

**Comment by justinlittman** [comment]
The permissions part of this ticket requires https://github.com/LD4P/sinopia_api/pull/179 be merged.
