### ISSUE TITLE
Only HB on 500

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#165]
Currently, HB alerts on all errors, including 400, 404, etc. This is very noisy.

HB should only alert on 500 errors (preferably excluding 500 errors that are deliberately raised from the MARC endpoint when there is an error in MARC processing).

**Comment by peetucket** [comment]
Found some documentation here on filtering: https://docs.honeybadger.io/lib/javascript/guides/reducing-noise/
