### ISSUE TITLE
SPIKE: Usage metrics

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_api#215]
Determine which of the requested usage metrics can be determined by querying Mongo.

Requested metrics: https://docs.google.com/document/d/1pnZ1QPbWfCEv57srQlVd6FxHnGYpBeVhk6kzs9B7SX0/edit#

Please document the queries. This ticket does not include any implementation.

**Comment by peetucket** [comment]
**From mongo console (tested on localhost):**

`docker exec -it sinopia_editor-mongo-1 mongo`

`use sinopia_repository`

## Quantity of users and resources
**Number of registered users**

`db.users.count()`

** Number of resources (not templates)**

`db.resources.find({types: { $not: {$eq: 'http://sinopia.io/vocabulary/ResourceTemplate'}}}).count()`

** Number of templates**
`db.resources.find({types: 'http://sinopia.io/vocabulary/ResourceTemplate'}).count()`

## Usage by period

**How many resources were created during specified time period**

There is a timestamp column in mongo for each document, but it is a "last touched" date, so is not necessarily the creation date.

**How many templates were created during specified time period**

There is a timestamp column in mongo for each document, but it is a "last touched" date, so is not necessarily the creation date.

**How many existing resources were (edited?) during specified time period**

Example below is Nov 2021, can adjust dates in ISO format:

```
db.resources.find({types: { $not: {$eq: 'http://sinopia.io/vocabulary/ResourceTemplate'}},
                   timestamp : { $gt:ISODate('2021-11-01'), $lt:ISODate('2021-11-30')}}).count()
```

**How many existing templates were (edited?) during specified time period**

Example below is Nov 2021, can adjust dates in ISO format:

```
db.resources.find({types: 'http://sinopia.io/vocabulary/ResourceTemplate',
                   timestamp : { $gt:ISODate('2021-11-01'), $lt:ISODate('2021-11-30')}}).count()
```

## Group Usage by period

**How many resources were created by group during specified time period**

There is a timestamp column in mongo for each document, but it is a "last touched" date, so is not necessarily the creation date.

**How many templates were created by group during specified time period**

There is a timestamp column in mongo for each document, but it is a "last touched" date, so is not necessarily the creation date.

**How many existing resources were edited during specified time period**

Example below is Nov 2021 for group 'stanford', can adjust dates in ISO format:

```
db.resources.find({types: { $not: {$eq: 'http://sinopia.io/vocabulary/ResourceTemplate'}},
                   timestamp : { $gt:ISODate('2021-11-01'), $lt:ISODate('2021-11-30')},
                   group: 'stanford'}).count()
```

**How many existing templates were edited during specified time period**

Example below is Nov 2021 for group 'stanford', can adjust dates in ISO format:

```
db.resources.find({types: 'http://sinopia.io/vocabulary/ResourceTemplate',
                   timestamp : { $gt:ISODate('2021-11-01'), $lt:ISODate('2021-11-30')},
                   group: 'stanford'}).count()
```

## User engagement

This is not the same as how many x were created; this is a measure of how many users were doing something on the app

**How many users logged in within a given time period**

I don't think we can get this from our data in Mongodb.  Perhaps Cognito?

**How many users saved at least one new resource within a given time period**

**How many users saved at least one new template within a given time period**

**How many users edited at least one existing resource within a given time period**

**How many users edited at least one existing template within a given time period**

## Group engagement

**Be able to get the user engagement metrics by group, like “how many users from group X logged in within a given time period”?**

I don't think we can get this from our data in Mongodb.  Perhaps Cognito?

## Feature usage

**How many Exports to ILS were performed within a given time period, and to which ILS?**

I don't think this is in Mongo?

**How many Conversions to MARC were performed within a given time period (this is also part of Export to** Catalog so would need to take that into account)

I don't think this is in Mongo?

**How many Load RDF transactions were there within a given time period?**

I don't think this is in Mongo?

## User location

**Total number of registered users by country, based on IP address they log in from plus would be nice to slice the User Engagement by country too**

I don't think we can get this from our data in mongo.  This would be perfect data to capture from Google Analytics.

## Template usage

**How many times was a given template used to create a new resource?**

`db.resources.find({types: 'RESOURCE_TEMPLATE_URI'}).count()`

e.g. 

`db.resources.find({types: 'https://Foobar.com'}).count()`

## Search metrics

**List the searches that produced zero results. This could assist in improving search feature.**

I don't think this data is in mongo

**Comment by justinlittman** [comment]
Did you consider the data in the `resourceMetadata` collection?

**Comment by peetucket** [comment]
I spoke too fast, thanks for the pointer - let me have a look.

**Comment by peetucket** [comment]
For some of the metrics (e.g. logged in users in a give time period), this may be possible to get from Cognito by connecting to Amazon Pinpoint Analytics, though this appears to incur an additional cost:

https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-pinpoint-integration.html
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-analytics.html

There is also logging of events in CloudTrail that could potentially be used to report: https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-now-supports-logging-for-all-api-calls-with-aws-cloudtrail/

**Comment by peetucket** [comment]
Note that the any queries that use the `timestamp` on the `resources` collection will pose a problem if a user asks for a previous time period.

For example, if you want to know the number of resources edited in Oct 2020, and you queried for 10-1-2020 to 10-31-2020, and one of the resources edited on Oct 15, 2020 was also edited in November of 2020, it would not be counted, as the single timestamp would have been updated to November.

It should instead look into the versions in the `resourcesMetadata` collection, search across all version timestamps, distinct the IDs and then count them.

**Comment by peetucket** [comment]
Reopen to adjust queries as noted in comment above
