### ISSUE TITLE
Sinopia User Endpoint

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_api#47]
To support the Editor dashboard, the API needs to support the following information for each user:

-  User preferences like name, email, and institution. Potentially custom diacritic keystrokes
-  User's history of the past 20 resources and templates. 
-  Search history of the user. 

User should only be able to view their current history and data, the API should check to see if the JWT is valid for that user only, i.e. even if I have a valid JWT I should not be able to access another user's information.

Should also investigate using Cognito [Groups](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html) for the group affiliation although we may want to store the group affiliation of a user because of the additional search flexibility that gives us.

**Comment by justinlittman** [comment]
Does all of this belong in API or should some (name, email, institution) come from Cognito?

**Comment by jermnelson** [comment]
> Does all of this belong in API or should some (name, email, institution) come from Cognito?

We can get the username and email but not the name or institution from Cognito.

**Comment by jcoyne** [comment]
Could a user have more than one affiliation?  What happens if someone moves from one institution to another?

**Comment by jermnelson** [comment]
Yes, users can multiple affiliations, i.e. A cataloger at Stanford could also be part of PCC. As brought up in 9/28 planning meeting, there could easily be a situation where a part-time employee is a cataloger at multiple institutions.

**Comment by jermnelson** [comment]
Closing with #58 being merged
